
comment:
  layout: "header, diff, files, footer"
  hide_project_coverage: false
  hide_branch_coverage: false
  hide_comparison: false
  
coverage:
  status:
    project: #add everything under here, more options at https://docs.codecov.com/docs/commit-status
      default:
        target: 98%
        threshold: 1%
        informational: false
        
ignore:
  - flowmazonbackend/flowmazonapi/Migrations