ignore:
  - flowmazonbackend/flowmazonapi/Migrations

coverage:
  status:
    project: #add everything under here, more options at https://docs.codecov.com/docs/commit-status
      default:
        target: 85%
        threshold: 1%
        informational: false