//This file binds client spans sent by Faro
//with spans generated by server side code;
// The code is taken from here:
// https://grafana.com/docs/grafana-cloud/monitor-applications/frontend-observability/quickstart/nextjs/

import { NextRequest, NextResponse } from 'next/server';
import { trace } from '@opentelemetry/api';

// because we may use 'request' in this function in the future:
// eslint-disable-next-line @typescript-eslint/no-unused-vars
export function middleware(request: NextRequest) {
  const response = NextResponse.next();
  const current = trace.getActiveSpan();

  // set server-timing header with traceparent
  if (current) {
    response.headers.set(
      'server-timing',
      `traceparent;desc="00-${current.spanContext().traceId}-${current.spanContext().spanId}-01"`,
    );
  }
  return response;
}
