# syntax=docker/dockerfile:1

FROM postgres:latest

ARG MIGRATIONS_PATH

# Copy migration scripts into the image
COPY ${MIGRATIONS_PATH} /docker-entrypoint-initdb.d/migrations

# Add a script to create the database and apply all migrations in order
COPY --chown=postres:postgres    ${MIGRATIONS_PATH}/createAndMigrateTestDB.sh /docker-entrypoint-initdb.d/01-create-and-migrate.sh

RUN chmod +x /docker-entrypoint-initdb.d/01-create-and-migrate.sh

EXPOSE 5432